version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flexistock_app
    ports:
      - "8000:80"  # Adapter pour exposer l'application sur le port 8000 (port HTTP)
    volumes:
      - .:/app      # Le répertoire de travail dans ton Dockerfile est `/app`
    environment:
      DATABASE_URL: "mysql://root:password@db:3306/flexistock?charset=utf8mb4"
    depends_on:
      - db
    restart: always # Pour redémarrer automatiquement en cas de problème

  db:
    image: mysql:8.0
    container_name: flexistock_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flexistock
    volumes:
      - db_data:/var/lib/mysql # Stocker les données de MySQL de façon persistante
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: flexistock_phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password # Mot de passe de l'utilisateur root MySQL
    depends_on:
      - db
    restart: always

volumes:
  db_data:
