parameters:
    # Application-specific parameters
    app.jwtsecret: '%env(JWT_SECRET)%'
    images_directory: '%kernel.project_dir%/public/uploads/'
    invoice_directory: '%kernel.project_dir%/var/invoices'
    avatars_directory: '%kernel.project_dir%/public/uploads/avatars'
    
    # Admin email and email sender
    admin_email: '%env(APP_MAINTENANCE_NOTIFICATION_EMAIL)%'
    from_email: '%env(APP_MAIL_FROM)%'
    
    # Maintenance notification settings
    app.mail_from: '%env(APP_MAIL_FROM)%'
    app.maintenance_notification_email: '%env(APP_MAINTENANCE_NOTIFICATION_EMAIL)%'
    # Email verification settings
    app.email_verification.from_email: '%env(APP_MAIL_FROM)%'
    # ... email verification settings
    
services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Service configuration for StockAlertService
    App\Service\StockAlertService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $mailer: '@mailer.mailer'
            $params: '@parameter_bag'

    # Service configuration for ReservationAlertService
    App\Service\ReservationAlertService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $mailer: '@mailer.mailer'
            $params: '@parameter_bag'

    # Service configuration for OrderNotificationService
    App\Service\OrderNotificationService:
        arguments:
            $mailer: '@mailer.mailer'
            $twig: '@twig'
            $urlGenerator: '@router'
            $adminEmail: '%admin_email%'
            $fromEmail: '%from_email%'

    # Service configuration for InvoiceService
    App\Service\InvoiceService:
        arguments:
            $invoiceDirectory: '%invoice_directory%'

    # Service configuration for EmailVerificationService
    App\Service\EmailVerificationService:
        arguments:
            $fromEmail: '%app.email_verification.from_email%'